Add first implementation to download xml and configure SP
wso2-incubator/identity-incommon-manager pull request #1
Opened 2018-12-07 08:44 UTC by sahanruwanga

## Purpose
This PR is the initial implementation for the project **InCommon Federation compliance for WSO2 IS**. This covers the basic requirement of downloading InCommon Metadata file, reading configuration data and Configuring Service Providers.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2018-12-07 12:49 UTC, ashensw requested changes

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt.stub/src/main/resources/InCommonMetadataManagementService.wsdl
> +</wsdl:definitions>
Add a new line

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/util/SchedulerContext.java
> +    private int refreshEnable;
Can't we change this to a boolean?

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt.ui/src/main/resources/META-INF/component.xml
> +</component>
Add a new line

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt.ui/src/main/java/org/wso2/carbon/identity/incommon/mgt/ui/client/InCommonManagementServiceClient.java
> +            stub.startConfiguration("https://md.incommon.org/InCommon/InCommon-metadata.xml", 60 * 60, 1);
It's better to move these URL and period to constants. Also this period should be configurable?

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt.ui/src/main/java/org/wso2/carbon/identity/incommon/mgt/ui/client/InCommonManagementServiceClient.java
> +        String serviceURL = serverURL + "InCommonMetadataManagementService";
Move this to a constant class.

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/InCommonMetadataManagementAdminService.java
> +    public void startConfiguration(String url, int period, int refreshEnable) {
Add method comments to all public methods if you have missed any.

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/util/HelperConstant.java
> +public class HelperConstant {
Shall we change this class name to a more meaningful name?  eg:`IncommonMgtConstants`

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/util/MetadataElement.java
> +public class MetadataElement {
Shall we change this class name to a more meaningful name since this is a constants class?

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/util/SPMetadataElement.java
> +public class SPMetadataElement {
Shall we change this class name to a more meaningful name since this is a constants class?

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/util/SchedulerContext.java
> +        periodInMillis = this.getPeriod() * 60 * 1000;
Shall we make these configurable?

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/validator/SignatureValidator.java
> +            File file = new File("/home/sahan/Documents/WSO2IS/new2-5.8-m6/wso2is-5.8"
Fix this file path to a relative path where you store the `incommon-metadata.xml` inside the server.

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/validator/ValidUntilValidator.java
> +        if (diff < 3 * 7 * 24 * 60 * 60 * 1000) {
Shall we move these time values to a constant and explain the login in a comment.

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/xmlhandler/XMLDownloader.java
> +            if (connection.getResponseCode() == 200) {
Use the `org.apache.http.HttpStatus` to get the constants as [here](https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint/src/main/java/org/wso2/carbon/identity/mgt/endpoint/client/SelfRegistrationMgtClient.java#L184)

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/xmlhandler/XMLDownloader.java
> +            } else if (connection.getResponseCode() == 304) {
Use the org.apache.http.HttpStatus to get the constants.

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/xmlhandler/XMLHandler.java
> +                    .getValue(MetadataElement.KEY_USE).equals("signing"))) {
Move this to a constant.

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/xmlhandler/XMLHandler.java
> +        // Read inCommon Signature to verify
Remove unnecessary commented codes.

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/xmlhandler/XMLHandler.java
> +        //        if (isReadingSignatureValue()) {
Remove unnecessary commented codes.

2018-12-07 12:49 UTC, ashensw commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/xmlhandler/XMLHandler.java
> +        // Send InCommon Signature to verify
Remove unnecessary commented codes.

2018-12-18 17:34 UTC, sahanruwanga commented on components/org.wso2.carbon.identity.incommon.mgt/src/main/java/org/wso2/carbon/identity/incommon/mgt/util/SchedulerContext.java
> +    private int refreshEnable;
'refreshEnable' is stored in db too. So I take it as either 1 or 0 instead of true or false. Isn't that okay?

2020-04-23 04:30 UTC, closed without merging